# x86_64 架构配置

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"


# ARM 架构配置

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"

[target.armv7-unknown-linux-musleabi]
linker = "arm-linux-musleabi-gcc"

[target.armv5te-unknown-linux-musleabi]
linker = "arm-linux-musleabi-gcc"

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-musleabi-gcc"

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"


# RISC-V 架构配置

[target.riscv64gc-unknown-linux-musl]
linker = "riscv64-linux-musl-gcc"
rustflags = ["-C", "link-args=-lm", "-C", "panic=unwind"]


# PowerPC64 架构配置

[target.powerpc64le-unknown-linux-musl]
linker = "powerpc64le-linux-musl-gcc"
rustflags = ["-C", "link-args=-lm", "-C", "panic=unwind"]


# MIPS 架构配置

[target.mips-unknown-linux-musl]
linker = "mips-linux-musl-gcc"
rustflags = [
    "-C",
    "target-feature=-crt-static",
    "-C",
    "link-arg=-dynamic",
    "-C",
    "link-arg=-Wl,--dynamic-linker=/lib/ld-musl-mips-sf.so.1",
    "-C",
    "panic=unwind",
]

[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-musl-gcc"
rustflags = [
    "-C",
    "target-feature=-crt-static",
    "-C",
    "link-arg=-dynamic",
    "-C",
    "link-arg=-Wl,--dynamic-linker=/lib/ld-musl-mipsel-sf.so.1",
    "-C",
    "panic=unwind",
]
